global: 
  resolve_timeout: 2m
receivers: 
  - 
    name: prometheus-msteams
    webhook_configs: 
      - 
        send_resolved: true
        url: "http://prometheus-msteams:2000/alertmanager"
route: 
  group_interval: 2m
  group_wait: 30s
  receiver: prometheus-msteams
  repeat_interval: 1h
