# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
rule_files:
  - dead-mans-snitch-rule.yml
  - linuxmetrics-alerts.yml  
scrape_configs:
  - job_name: "prometheus"
    basic_auth:
      username: admin
      password: devops123
    static_configs:
      - targets: ["prometheus:9090"]


  - job_name: Docker-containers-server
    static_configs:
      - targets: ["3.7.65.152:9100"]

  - job_name: grafana-server
    static_configs:
      - targets: ["13.235.49.179:9100"]

  - job_name: teleport-server
    static_configs:
      - targets: ["teleport-metrics.myarts.live:9100"]        

        

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]


  - job_name: 'cadvisor-containers'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']


  - job_name: 'app-containers'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.7.65.152:8080']

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["65.2.5.195:15692"]

  - job_name: 'Web-apps'
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
            - https://github.com
            - https://google.com
            - https://teleport-security.akriviahcm.io
            - https://monitor.myarts.live/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115 

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox:9115']

  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - 3.7.65.152:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 3.7.65.152:9121

